### ISSUE TITLE
Params URL

### ISSUE THREAD

**Issue by erjezus** [groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#40] opened 2019-08-20 06:33 UTC
Forum: https://forum.groupdocs.com/t/params-url/7489/2
> I need to load a document in the viewer by passing the name of the document in the url. The documentDefault parameter is static and I need to change it dynamically.

I need to go through the URL the name or path of the document to display or set the documentDefault attribute. Could you tell me how? Thanks

**Comment by egorovpavel** [comment] 2019-08-21 13:04
Hi @erjezus.  As far as I understand, you want to customize viewer in a way that it will be able to open a document using some kind of identifier passed in URL. I prepared an example of this use case in a separate [branch  ](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/tree/custom-viewer-example) (also [check out](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/pull/41/files) what was added/changed). 

This example expects to receive a URL of the document in a query string. EX:

http://localhost:8080/viewer/?url=https://calibre-ebook.com/downloads/demos/demo.docx

then it downloads this file to a server and opens it in Viewer.

You can modify [constructor logic](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/blob/custom-viewer-example/client/apps/viewer/src/app/custom-viewer/custom-viewer.component.ts#L15-L31) to fit your use case. For example, instead of using URL to download and open a downloaded file you can use another identifier or filename to open files you already have at your server.

Let me know if this solution works for you.

**Comment by erjezus** [comment] 2019-08-21 16:22
Hello, I am deploying the application with the war profile with finalName viewerDocument. Currently I get this error when starting.

![ERROR](https://user-images.githubusercontent.com/19823681/63449463-8469fb80-c440-11e9-8b69-aa36fafdebc5.JPG)

Thanks.

**Comment by egorovpavel** [comment] 2019-08-22 07:44
@erjezus by default we assume that API located at http://localhost:8080. In order to change this to your custom endpoint simply modify this [line](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/blob/custom-viewer-example/client/apps/viewer/src/app/app.module.ts#L10)

**Comment by egorovpavel** [comment] 2019-08-23 08:26
Hi @erjezus, Let us know if this solution works for you and we can close this issue.

**Comment by erjezus** [comment] 2019-08-26 07:40
Hi, the solution works correctly. But I need the viewer options bar too. Also if the document contains a URL as hyperlink does not work.

**Comment by mjim79** [comment] 2019-09-25 07:13
Hi @egorovpavel,

Any update regarding this issue? We are waiting for two issues:

1. The final solution with the viewer options bar.
2. If a document contains an URL as hyperlink, the link doesn’t work.

Thank you!

**Comment by egorovpavel** [comment] 2019-09-25 09:03
Hi @erjezus. The provided branch was intended to showcase the way to customize the behavior and appearance of the GroupDocs.Viewer application.  I updated this branch and reverted to the original view and stylings. 

In case you need to customize the original appearance just edit files related with custom component https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/tree/custom-viewer-example/client/apps/viewer/src/app/custom-viewer

Regarding the issue with the links in the document I was unable to reproduce this issue, please provide a document where we can reproduce this issue.

**Comment by erjezus** [comment] 2019-10-11 11:47
These two documents contain url, the viewer shows them as text. We have performed tests even with the test viewer (https://products.groupdocs.app/viewer)

[Files.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/files/3717337/Files.zip)

**Comment by egorovpavel** [comment] 2019-10-14 16:20
Hi @erjezus, I tried both files and was able to view and click on links
![image](https://user-images.githubusercontent.com/737110/66766623-935caf80-eebf-11e9-94fd-3192a4ea43c9.png)

Make sure that you are using correct rendering mode (`htmlMode = true`) in `configuration.yml` 

[Viewer configuration options](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#viewer-configuration-options)

**Comment by erjezus** [comment] 2019-10-23 10:00
Hi @egorovpavel , Try the following pdf document please. In the configuration it is defined as html. Thanks.

![imagen](https://user-images.githubusercontent.com/19823681/67381673-97a65e00-f58c-11e9-9651-3a8482972662.png)

[HIPERLINK.pdf](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/files/3761621/HIPERLINK.pdf)

**Comment by egorovpavel** [comment] 2020-01-09 06:51
@erjezus Please try in the latest version of GroupDocs.Viewer.

**Comment by koleslena** [comment] 2020-01-11 09:39
Hi @erjezus , the problem was reproduced in the lastest version of groupdocs-viewer, so we reported the bug for groupdocs-viewer team.

**Comment by koleslena** [comment] 2020-01-14 11:25
Hi @erjezus , I added fix for rendering links from pdf files.

**Closed** 2020-01-14 11:28 UTC
Labels: help wanted
